language: generic
script: bash ./deploy.sh
env:
  global:
  - COMMIT_AUTHOR_EMAIL: jyasskin+travisci@google.com
before_install:
- openssl aes-256-cbc -K $encrypted_5e5c573e47c6_key -iv $encrypted_5e5c573e47c6_iv
  -in deploy_key.enc -out deploy_key -d
