language: generic
script: bash ./deploy.sh
env:
  global:
  - COMMIT_AUTHOR_EMAIL: jyasskin+travisci@google.com
  - secure: gnb7VLiaXOzbEYMAsfsefGwKJ66S455dIJuqv3V9H732lt+nfGOQ994CyaVrP13qP1KW2JHqfk2oHipp68upNtBrKjw6ukxUrGYEbtnb0+uEnyefQQ2AtZmSODxKmjI9KpyooyimSkW5tH5mSzvWY016KnqveKFERkuhQb77gVvU9vmwRN7gRBTHUu9CBBuziaFj4vhbGplbQbmhXPB1Sa5Z32flM4/SxqKgjweezp8BOCHEKrR7HRxuTbv9W08OqXlMo7NJEGtcfZ0zknSObbHueRvv6ZjfW6+UMpFqmq9JLCnrc/Y+pqHABTtzVRRdzJOv3GKX0Trzma1pvyRhNDJKEdl9K84SfDbq3TBTI6gpfebmybHiljpe41ZYo8HmlCygCAxYxYGsK4bKOcKR5c8+/O1CiVUWnlWCz5abHyChqJoXimYla9CO/ziCyYvBQ6B/9xlVIsREOuDSoIH/ITQjN+alBeifQ/O/gt1mVwldcslLbx41xfJztjz0UhrkKGbFZUIa2qo+2amHVIpbuKK9PoXgUWmOThSbEf9oevyc2gGaFlrWRgQrRoUJTLZij+uM2Pal3uPfI6Zv/BjraHUKyAKSdDx0U/EdSu93Qg3GLRsfaQFFN5C27Rf7NDiTNTJuahmamXwz534r6AV2oJwFNoauri0RPKMbndH7YqM=
